services:
  postgres-products-gama:
    image: postgres:15-alpine
    container_name: postgres-products-gama
    environment:
      POSTGRES_DB: db_products
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: 123456
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --lc-collate=es_ES.UTF-8 --lc-ctype=es_ES.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_products_data_gama:/var/lib/postgresql/data
      - ./db-scripts/products:/docker-entrypoint-initdb.d
    networks:
      - gamacommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fazt -d db_products"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-orders-gama:
    image: postgres:15-alpine
    container_name: postgres-orders-gama
    environment:
      POSTGRES_DB: db_orders
      POSTGRES_USER: fazt3
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - postgres_orders_data_gama:/var/lib/postgresql/data
      - ./db-scripts/orders:/docker-entrypoint-initdb.d
    networks:
      - gamacommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fazt -d db_orders"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-payments-gama:
    image: postgres:15-alpine
    container_name: postgres-payments-gama
    environment:
      POSTGRES_DB: db_payments
      POSTGRES_USER: fazt2
      POSTGRES_PASSWORD: 123456
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --lc-collate=es_ES.UTF-8 --lc-ctype=es_ES.UTF-8
    ports:
      - "5433:5432"
    volumes:
      - postgres_payment_data_gama:/var/lib/postgresql/data
      - ./db-scripts/payments:/docker-entrypoint-initdb.d
    networks:
      - gamacommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fazt -d db_orders"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-users-gama:
    image: mysql:8.0
    container_name: mysql-users-gama
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_users
    ports:
      - "3308:3306"
    volumes:
      - mysql_users_data_gama:/var/lib/mysql
      - ./db-scripts/users:/docker-entrypoint-initdb.d
    networks:
      - gamacommerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  # ===========================================
  # KAFKA CLUSTER
  # ===========================================
  kafka-1-gama:
    image: 'bitnami/kafka:3.3.2'
    container_name: kafka-1-gama
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=xMohcG_6SLqdeJSbJeWjNA
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1-gama:9091,2@kafka-2-gama:9091,3@kafka-3-gama:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1-gama:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    ports:
      - "9092:9092"
    volumes:
      - kafka_1_data_gama:/bitnami/kafka
    networks:
      - gamacommerce-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9192", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka-2-gama:
    image: 'bitnami/kafka:3.3.2'
    container_name: kafka-2-gama
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=xMohcG_6SLqdeJSbJeWjNA
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1-gama:9091,2@kafka-2-gama:9091,3@kafka-3-gama:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2-gama:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    ports:
      - "9094:9094"
    volumes:
      - kafka_2_data_gama:/bitnami/kafka
    networks:
      - gamacommerce-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9192", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka-3-gama:
    image: 'bitnami/kafka:3.3.2'
    container_name: kafka-3-gama
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=xMohcG_6SLqdeJSbJeWjNA
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1-gama:9091,2@kafka-2-gama:9091,3@kafka-3-gama:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3-gama:9090,EXTERNAL://${HOSTNAME:-localhost}:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    ports:
      - "9096:9096"
    volumes:
      - kafka_3_data_gama:/bitnami/kafka
    networks:
      - gamacommerce-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9192", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ===========================================
  # OBSERVABILITY STACK
  # ===========================================
  elasticsearch-gama:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch_springboot-gama
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic123
        # ✅ AGREGAR ESTAS CONFIGURACIONES
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data_gama:/usr/share/elasticsearch/data
    networks:
      - gamacommerce-network

  kibana-gama:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana_springboot_gama
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      #Needed to create a token in http://localhost:9200/_security/service/elastic/kibana/credential/token/token1?pretty with basic auth with elastic user
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTpQM1Nkam5uLVJMMjk1RWR0UG43RGdB
    volumes:
      - ./docker-config/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - kibana_data_gama:/usr/share/kibana/data
    depends_on:
      - elasticsearch-gama
    networks:
      - gamacommerce-network
  logstash-gama:
    image: docker.elastic.co/logstash/logstash:8.3.3
    container_name: logstash_springboot_gama
    volumes:
      - ./docker-config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./docker-config/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic123
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: elastic
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: elastic123
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
    networks:
      - gamacommerce-network
    depends_on:
      - elasticsearch-gama
  # ===========================================
  # CORE MICROSERVICES
  # ===========================================
  config-service-gama:
    image: rpantax/config-service:latest
    container_name: config-service-gama
    ports:
      - "8888:8888"
    networks:
      - gamacommerce-network
    restart: unless-stopped

  discovery-service-gama:
    image: rpantax/discovery-service:latest
    container_name: discovery-service-gama
    ports:
      - "8761:8761"
    networks:
      - gamacommerce-network

  # ===========================================
  # BUSINESS MICROSERVICES
  # ===========================================
  user-service-gama:
    image: rpantax/user-service-gama:latest
    container_name: user-service-gama
    depends_on:
      mysql-users-gama:
        condition: service_healthy
      discovery-service-gama: # ✅ AGREGAR DEPENDENCIA
        condition: service_started
    networks:
      - gamacommerce-network
    ports:
      - "8082:8082"
    restart: unless-stopped

  product-service-gama:
    image: rpantax/products-service-gama:latest
    container_name: product-service-gama
    depends_on:
      postgres-products-gama:
        condition: service_healthy
      config-service-gama:
        condition: service_healthy
      discovery-service-gama:
        condition: service_started
    networks:
      - gamacommerce-network
    ports:
      - "8081:8081"
    restart: unless-stopped
  credit-card-processor-service-gama:
    image: rpantax/credit-card-processor-service-gama:latest
    container_name: credit-card-processor-service-gama
    depends_on:
      discovery-service-gama:
        condition: service_started
    networks:
      - gamacommerce-network
    ports:
      - "8084:8084"
    restart: unless-stopped
  orders-service-gama:
    image: rpantax/orders-service-gama:latest
    container_name: orders-service-gama
    depends_on:
      postgres-orders-gama:
        condition: service_healthy
      config-service-gama:
        condition: service_healthy
      kafka-1-gama:
        condition: service_healthy
      kafka-2-gama:
        condition: service_healthy
      kafka-3-gama:
        condition: service_healthy
      discovery-service-gama:
        condition: service_started
    networks:
      - gamacommerce-network
    ports:
      - "8085:8085"
    restart: unless-stopped
  payment-service-gama:
    image: rpantax/payment-service-gama:latest
    container_name: payment-service-gama
    depends_on:
      postgres-payments-gama:
        condition: service_healthy
      config-service-gama:
        condition: service_healthy
      kafka-1-gama:
        condition: service_healthy
      kafka-2-gama:
        condition: service_healthy
      kafka-3-gama:
        condition: service_healthy
      discovery-service-gama:
        condition: service_started
    networks:
      - gamacommerce-network
    ports:
      - "8086:8086"
    restart: unless-stopped

  api-gateway-gama:
    image: rpantax/api-gateway-service:latest
    container_name: api-gateway-gama
    networks:
      - gamacommerce-network
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  gamacommerce-network:
    driver: bridge

volumes:
  postgres_products_data_gama:
  postgres_orders_data_gama:
  postgres_payment_data_gama:
  mysql_users_data_gama:
  kafka_1_data_gama:
  kafka_2_data_gama:
  kafka_3_data_gama:
  kibana_data_gama:
  elasticsearch_data_gama:
    driver: local
